# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b4ae6609dbd97ddd5df02c3360357b53d48721f07c9f1be660fd22de91311145ef2a2ec63ddd60368d678ed91e28a0f3d238285a3cc9745320d992e7b59e5e

test:
  secret_key_base: ab34d5c8fd193e0cb42eb2c1592e86439ade46c9705a9da45e0de9354274eed057ef00488be08e374d65e79c628f3f560c2d46186decbca96feac1ba54147324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
